### ISSUE TITLE
CDN builds and integration?

### ISSUE THREAD

**Issue by dylans** [dojo/meta#158]
CDNs are typically used to support ease of deployment, trying out Dojo, and for web-based editors. A few questions:

1. Do we care about CDN builds for Dojo 2?
2. If so, what CDNs should we support (e.g. JSFiddle relies on cdnjs, or Google's CDN, or just something like https://cdn.rawgit.com/ ?)
3. While things like JSFiddle support TypeScript, I have no idea how they load modules so we would need to investigate that if we want to support things besides Plunkr.

**Comment by matt-gadd** [comment]
It was fairly straightforward for me to get `widget-core` going with codepen using the loader. This was using `unpkg` as a cdn (as it caches from npm), but it would be similar for any other cdn or web base editor I imagine. Example here: http://codepen.io/mattgadd/pen/zZPxNB?editors=0010

**Comment by matt-gadd** [comment]
@dylans here is a minimal todo-mvc codepen using dojo 2: http://codepen.io/mattgadd/pen/GWQvEE?editors=0010

**Comment by kitsonk** [comment]
I am not sure that this will require specific features from us.  Was the [dojo/web-editor](https://github.com/dojo/web-editor) there are various NPM CDNs that can be used by people if needed.  Since there isn't any real clear action and if there is any action, we will fold it into how we approach web-editor.  I am closing this.
