### ISSUE TITLE
Create 'cli-build-widget'

### ISSUE THREAD

**Issue by rishson** [dojo/meta#163]
We should consider creating a `cli-build-widget` repo/package.
This package could do things such as:

- create custom element files for a widget (if not found) and possibly update if needs be
- re-run the css typings generation for the widget

**Comment by bitpshr** [comment]
After writing a lot of components and always copy / pasting some other component to get started, I would end up using this.

Going to assign this to myself, happy to take a stab at it.

**Comment by agubler** [comment]
Okay 👍 Can you give it a go as a separate command?

**Comment by bitpshr** [comment]
@agubler: I wasn't sure how to ask for a review since there's no corresponding dojo repo, but an initial, tested implementation of cli-create-widget can be be found [here](https://github.com/bitpshr/cli-create-widget). Would be great to get your thoughts. I know you mentioned that we should create a common package for cli-create-app and cli-create-widget since the latter leverages the former, but I need some more information as to what you were thinking architecturally.

**Comment by agubler** [comment]
@bitpshr I'll give this a look over tomorrow AM 😀
