### ISSUE TITLE
Use @dojo scope packages for npm?

### ISSUE THREAD

**Issue by dylans** [dojo/meta#21]
Should we start using @dojo for our packages on npm? We have @dojo registered.

**Comment by kitsonk** [comment]
Scoped packages are still problematic with some versions of npm. What other
projects are doing seems to be to have both a strategy of the "standard"
distribution in the normal namespace and variant distributions in the
namespaces bit (e.g. `@dojo/core-amd` and `dojo-core`) but I don't see us
being able to take advantage of that until we sort out our distributions.

Right now, I am not sure of what advantage it provides us other than saying
we have a namespace. Maybe ai am missing something though.

**Comment by novemberborn** [comment]
> Scoped packages are still problematic with some versions of npm.

It's supported in v2. v1 is no longer maintained and Node.js has stopped shipping it as of [v0.10.44](http://nodejs.org/en/blog/release/v0.10.44/) because of this.

That said currently public scoped modules are not included in the replication stream, see this conversation: <https://twitter.com/terinjokes/status/721210339765825536>.

Using `@dojo` would guarantee the package names can be what we want them to be, without having to argue over (il)legitimate uses of the `dojo-` prefix.

**Comment by kitsonk** [comment]
Thanks.

RxJS does some narrow packages in the public namespace, and does more "mega" packages in the `@reaxtivex` namespace.  I suspect having it being mixed would likely where we will end up.

**Comment by kitsonk** [comment]
We should merge this conversation with #18.
