### ISSUE TITLE
Supporting Dojo 2 widget in a Dojo 1 "App"

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#212]
**Enhancement**

We have supported the use cased of using a Dojo 1 Dijit in a Dojo 2 application, but we likely need to investigate the reverse use case.

**Use Case**

As a developer, I have created a Dojo 2 widget which I want to add as a child of a Dojo 1 widget.  (For example, I want to use the `@dojo/widget/button/Button` as a child of a  `dijit/layout/ContentPane`).

**Comment by kitsonk** [comment]
Creating this as an epic, as there is likely specific tasks to perform related to this work.

**Comment by edhager** [comment]
My work-in-progress is here: https://github.com/edhager/Dojo1AppWithDojo2Widgets

I built today's master branch of @dojo/widget-core and @dojo/widgets and included them in the `deps` directory.  I wanted to work with the latest widget-core updates.

Here are some observations.  If I am doing anything wrong, please let me know.
- I needed to configure very little package mapping in the Dojo 1 loader config but unfortunately, I had to include this:
```
{ name: 'pepjs', location: '../pepjs/dist', main: 'pep' }
```
- It looks like I have to individually load the CSS for each Dojo 2 widget that I use. 
```html
<link rel="stylesheet" href="node_modules/@dojo/widgets/button/styles/button.m.css">
```
I haven't really tried working with a theme yet. I plan on adding some more complicated widgets before messing around with themes and before analyzing how I am using the Dojo 2 widgets.

**Comment by kitsonk** [comment]
* I wonder if the shim AMD helper modules would help with the configuration that @rorticus has landed.  It would also deal with other shims that would be needed when running under AMD, which other packages depend upon (like the IntersectionObserver).
* Yes, there is no "main" CSS for the widgets, because the Dojo 2 build tool automagically detects the dependencies.  I would be resistant to add one, because we do want the code widgets to be separable, but at the same time, we have to manually add them for the theme though.  I think it still raises a bigger question about how we manage themes... I still feel it is a bit clunky as there is clearly a way to detect the dependencies with the bases styles at build time, but no way of doing the same for themes...  Either way, I think this whole bit warrants further discussion.

**Comment by kitsonk** [comment]
@matt-gadd pointed out that we had thought about creating something that generated a "Dijit" surface like API that would wrap Dojo 2 widgets and would be part of [dojo/interop](https://github.com/dojo/interop), which of course would worry about all the stuff needed, an analogue for the other wrapper.

**Comment by edhager** [comment]
Take a look at dojo/interop#17 for the current work-in-progress.

**Comment by edhager** [comment]
A decision was made to change direction with this ticket.  Rather than wrapping Dojo 2 widgets for use in Dojo 1, we are going to promote building Dojo 2 widgets as custom elements and using those custom elements in Dojo 1 applications.

I created a reference application to experiment in: https://github.com/edhager/Dojo1CustomElements.

I decided to use a loader plugin to load the custom element definition.  People familiar with Dojo 1's loader will want to specify the dependency on a custom element in the module that is using the custom element.  Here is an example: https://github.com/edhager/Dojo1CustomElements/blob/master/myapp/Tab1.js#L3-L4.  

Here is the loader plugin I created: https://github.com/edhager/Dojo1CustomElements/blob/master/myapp/customElement.js.  Because the custom element definition is not an AMD module and it is used indirectly as an HTML tag or as a string passed to `document.createElement()`, the load order of the custom elements relative to one another or relative to the AMD modules is not important.  The plugin inserts the `<link>` elements in the `<head>` element.  An advantage of using a loader plugin, the loader will make sure the custom element definitions are loaded only once per page load.

Because the custom element definitions built from Dojo 2 widgets are not in AMD modules, they will be ignored by the Dojo builder and will not be included in a Dojo 1 bundle.
