### ISSUE TITLE
Issue with debugging CSS classes

### ISSUE THREAD

**Issue by sebilasse** [dojo/meta#243]
When I `dojo build -m dev -w memory -s` and look in the browser console to debug a CSS class I noticed that all classes from different CSS files show the same CSS file as source. This seems to be the first stylesheet loaded.

E.g. in this screenshot the rule does _not_ come from `tab-controller.m.css` (as indicated) but from `toolbar.m.css`

<img width="288" alt="bildschirmfoto 2018-03-17 um 11 20 09" src="https://user-images.githubusercontent.com/750300/37554218-ba497cc8-29d5-11e8-8f10-3d4a9ce39449.png">

**Comment by agubler** [comment]
@sebilasse Hmmm that is really strange as it seems to worked as expected on Chrome, Firefox, Edge - however on Safari it isn't mapping back to the source CSS. Seems like it could be an initial with safari rather than the CSS sourcemaps given it works across those other browsers.

I'll move the issue over to @dojo/cli-build-app for further discussion

**Comment by agubler** [comment]
Issue moved to [dojo/cli-build-app #74](https://github.com/dojo/cli-build-app/issues/74) via [**ZenHub**](https://www.zenhub.com/)
