### ISSUE TITLE
Dojo 2 and ES6 Modules

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#26]
While we will likely continue to prefer AMD/UMD for module loading, it is entirely conceivable that people might want to utilise Dojo 2 in ES6 Modules and we should try to provide as much functionality as possible.

I propose we only support targeting ES6+ with the ES6 module format (so we may need to complete #25 before we can fully complete this).

Things I think we should do:

- [x] Update the Gruntfile to allow generation of an ES6 module build.
- [x] Test loading the modules via SystemJS and see how they behave.
- [x] Identify any considerations for using the AMD plugin API and what impacts that would have on using with SystemJS and if there is any way to support a similar API with SystemJS.

**Comment by Tomdye** [comment]
Core PR raised for part 1: https://github.com/dojo/core/pull/146

**Comment by Tomdye** [comment]
### Module packaging
No point using `ES` modules because `SystemJS` then requires a transpiler (babel / traceur / typescript). Better to use the `grunt dist-es6` command to build a `UMD` packaged `ES6` build.

### System Config
To load with SystemJS we need to set up a small amount of config:

``` javascript
System.config({
	transpiler: false,
	defaultJSExtensions: true,
	meta: {
		'core/*': {
			scriptLoad: true
		}
	}
});
```
- The `scriptLoad` argument tells `SystemJS` to use script tags rather than XHR's to load our modules. It will auto-detect that the modules are `AMD` so there is no need to specify this here.
- The `defaultJSExtensions` flag indicates that module names should have `.js` appended to them, this fixes an issue where requiring `core/request` returns the directory listing of the request folder rather than the `request.js` module.

### Module loading
You can load a `js` file via `System.import('main');`
I was able to get a sample `main.js` file to load of the top-level `dojo/core` packages using `Promise.all` and array destructuring as follows (this does not force the use of an ES6 transpiler):

``` javascript
Promise.all([
	System.import('core/DateObject'),
	System.import('core/Evented'),
	System.import('core/Map')
]).then(([
	DateObject,
	Evented,
	Map
]) => {
	// Modules are loaded
})
```

Alternatively, the same will work using the `require` format:
``` javascript
define([
 	'core/DateObject',
 	'core/Evented',
 	'core/Map'
 ], (
 	DateObject,
 	Evented,
 	Map
 ) => {
 	// Modules are loaded
});
```

### Gotchas
`SystemJS` appears to run a regex against all loaded code no matter what format in order to pre-load any inline `require` calls. For example, in `text.ts` we conditionally load `fs` when `has('host-node')` is true. `SystemJS` finds the `require` call and attempts to preload the module. To get around thus we need to use an interim variable to represent `require`, this fools the regex. (reminds me of when you had to do `dojo['require']` to achieve similar in Dojo)

``` javascript
const nodeReq = require.nodeRequire || require;
const fs = nodeReq('fs');
```

**Comment by Tomdye** [comment]
The `SystemJS` plugin API is very different from our own:
https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md

If wishing to use the `System.import` format, it would be better to recomend that users simply use the already established SystemJS plugins for text, css etc.. There are two formats that can be used:
``` javascript
// 1. Specifying plugin in import
System.config({
	map: {
		text: 'core/text'
	}
});
System.import('text/path/file.txt!text'); // Text plugin specified

// 2. Specifying plugin to use via config
System.config({
	map: {
		text: 'core/text'
	},
	meta: {
		'text/path/*.txt': {
			loader: 'text'
		}
	}
});

System.import('text/path/file.txt') // Text plugin used automatically;
```

**Comment by kitsonk** [comment]
@Tomdye do you think there is any merit in considering adding the ability to the dojo/loader to load ES6 modules based on the current [WhatWG ES Module Loader specification](https://github.com/whatwg/loader)?

This would give people an easy way to use Dojo 2 with other ES6 modules without requiring their browser to support loading the modules (or using SystemJS).  In my mind, that was the main use case for trying to get Dojo 2 loading under SystemJS.

**Comment by Tomdye** [comment]
@kitsonk I believe it would need to `transpile` any loaded modules into a different format the same way that `systemJS` does as `import` and `export` will not work.

**Comment by Tomdye** [comment]
@matt-gadd is this issue still valid at all?

**Comment by kitsonk** [comment]
Closing for now, unless we have further actions.
