### ISSUE TITLE
Modularity of CSS

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#28]
One of the challenges with modular code is that it also can be a challenge to manage CSS in a modular way and be able for code to be explicit about what CSS is required.  Web Components solves this problem by integrating the logic (JavaScript), structure (HTML) and presentation (CSS) into a single entity which is loaded.

Since the direction of Dojo 2 isn't to solve this encapsulation problem via the Web Components architecture we need another mechanism for managing CSS.  The options I can see we might consider:
- Package Level CSS - Each package would have the CSS for all the widgets that it contains and additional themes could/would be loaded on top of the base CSS.  A pre-processor can be used for making it easy to maintain.  The challenges with this is that it becomes difficult to build time optimise any of the CSS and it becomes an all or nothing proposition.
- Adopt [css-modules](https://github.com/css-modules/css-modules) - A specification of how to modularise CSS and keep it easily tied to the code.  This has the advantage of making the CSS dependencies clear.  This would require an AMD plugin, one that may even integrate with a pre-processor, and do a build optimization step.  Because a definitive dependency graph could be determined at build time, this likely would end up in fairly well optimised built CSS.
- Follow a pattern, like [Radium](https://github.com/FormidableLabs/radium), which favours inline styles which can be expressed in a syntax similar to CSS, but calculate and set the styles at DOM rendering time.  This has the advantage of logic being able to manipulate the styling.

There maybe other patterns we could consider, but these are the ones that come to my mind.

**Comment by devpaul** [comment]
As a developer, I would like a way of skinning my components using CSS in a way that is decoupled from a package-level hierarchy while maintaining a familiar CSS syntax that myself, designers, and others are used to communicating.

I think we will only be talking about component libraries as I imagine application developers will continue to leverage package-level styles to unify their overall look and feel.

I took a look at css-modules and Radium. Of the two, I like the approach css-modules uses to create unique identifiers for css class names. Radium's approach is compelling for a vdom, but we recommend against what Radium does best -- individually styling each component. Add to that, the CSS is written in JavaScript making it unfriendly to CSS compilers and more difficult to play w/ styles in the browser.

I'm thinking we can tie css-modules into Dijit's component system with a factory capable of taking the default export from the CSS and adding it as a class property to the root container of the widget.

```css
:export {
    default: .parent;
    otherSkin: .anotherSkin;
}
.parent {
   /* styles */
}
```

```javascript
import styles from './styles.css'

@Skin(styles)
class Widget {
    render() { /* stuff */ }
}
```

The factory could also add methods to support reskinning the component, but it might be better to make a new class for each differently skinned component. This makes component building more factory-like and abstracts away some of the magic.

While we may not be looking at the ShadowDOM at the moment, I think the import syntax used with css-modules can also be leveraged by a tool to load the css dependency as part of the ShadowDOM. However, if we wanted to move this responsibility into Dijit and not rely on a build step to support ShadowDOM, we can move the css-module loader into the component factory.

```javascript
@Skin('./styles.css', 'otherSkin')
class Widget {
    render() { /* stuff */ }
}
```

Once the CSS module is known to Dijit, it can create ShadomDOM nodes simply by informing the factory how it should load CSS (e.g. as a <link> in the ShadowDOM or via css-modules plugin/loader).

The last example is the most compelling to me. It feels simple to write, is easy to reskin a component, is ShadowDOM ready, and should be friendly to pre-processors and optimization.

**Comment by kitsonk** [comment]
I would be really reticent utilise ShadowDOM for this, at this time.  While I get the concept, I think the use case is potentially more useful for i18n.  Even then, I am not convinced by the browser support.  It is only available in Chrome/Opera/Android Chrome.  It is behind a feature flag on Firefox for at least the next 3 releases.  It is being considered for Edge, but it is likely to be done, but that means Edge 15 might be the earliest we see it and there is yet to be clear view of it on Safari/WebKit.

I think we should do some sort of proof of concept of the CSS decorator though.  To see how it might integrate.  I am in the process of getting dojo/widgets available and we should, for now, do that as a separate branch there.  I will open another issue for that, but I will put this issue on hold for now while we do further investigations.

**Comment by dylans** [comment]
For what it's worth, there was a meeting in January or February of this year at the relevant standards group where both Shadow DOM and Custom Elements had a pretty significant refactor of their specs, and the representatives of all of the major browser vendors committed to implementing the current version of these specs this year. This is not me making a case for using or not using them, just that the current version of the spec. is very likely what we will see in all browsers by the end of 2016.

**Comment by kitsonk** [comment]
@devpaul I just realised, we can't use decorators, as we aren't using ES6 Classes.  We are using `dojo/compose`.  It would be a major step backwards to constrain our widgeting system by using ES6 classes.

**Comment by Tomdye** [comment]
I would vote for using modular CSS / LESS / SCSS and for it to be kept separate from the HTML and the JS. Style instructions should be a separate concern in my mind. A few thoughts / examples below from past projects. Especially seeing as most enterprise users of the Dojo toolkit want to re-style it immediately to fit their companies brand guidelines.

### Modularising
I've always worked with the principle that **every** component `LESS` file should start with the component's `className`. ie.

``` less
// likeButton.less
.likeButton {
// likeButton styles here
}
```
This ensures that the styles do not leak outside of the desired target. No magic or JS needed to assign these classNames because they shouldn't be changing.

### Class names
In the past I've always used `camelCase` class names for module names and all custom css classes. `hyphenated` class names were always saved for theme-wide classes / mixins. This shows a distinction between localised `app` classes and theme / structure classes. This also helps when choosing which class names to use when writing tests, ie. you would not make selections using the hyphenated classes, only the camelCased ones.

``` html
<div class='buttonHolder action-buttons'>
   <button class='submitButton call-to-action'>Click me</button>
</div>
```
``` less
// buttonHolder.less
.buttonHolder {
   .submitButton {
      float: right;
   }
}

// theme/components.less
.action-buttons {
   padding: @themed-component-padding;
}
.call-to-action {
   font-weight: bold;
}
```

### Theming
At my last company we themed Dijit twice, using `LESS` the first time I was young and naive so simply wrote claro-overrides which were loaded after all of Dojo's CSS and were mostly more specific thus overriding. This approach wasn't ideal.

The second time, I properly considered the layout and theming of our projects CSS files and went for a different approach, one that I feel may be relevant here:

I in-housed all of the `claro` code and turned it into a flat (truly flat) theme, just white backgrounds and borders and removed all mentions of `claro`. I then prefixed all the `LESS` variable names with `dijit`, `dojo` and `dojox` respectively. This gave me a highly themable base.
The applications style structure then contained the following files under it's themes directory:
ie. /themes/dark

- `_palette` - list of 'private' colours, ie. `@_brand-green: #60b044`
- `colorVariables` - list of prefixed colours, giving usable names to the pallete files ie.
``` less
@themed-button-color: @_brand-green; 
@themed-button-color-hover: lighten(@_brand-green, @themed-hover-lighten-percentage); 
```
- `dijitPatch` -  changes to structure of flat theme
- `dijitColourPatch` - list of colour assignments ie.
``` less
@dijit-button-background-color: @themed-button-color:
@dijit-button-border-color: darken(@themed-button-color, 20%):
```
- `components.less` - the theme components
- `mixins.less` - the theme mixins
- `theme.less` - imported 'all the things' ie.
``` less
@import '../dojo/theme';
@import 'dijitPatch';
@import 'dijitColorPatch';
@import 'components';
@import 'mixins';
@import '../app/components';
```

The `colourVariables` file provided all of the variable names I needed to theme my whole application, thus all of my application specific `LESS` code would ONLY use those . All we needed to do in order to create a new theme, was create a new folder under `themes` and alter the listed files.

The nice side of this is that you only need to build and import a single `.css` file. If an app has multiple themes you simply build separate `theme.css` files under `dark`, `light`, `badger` etc... and `load` / `unload` them when switching themes.

**Comment by dylans** [comment]
I would replace less with Stylus or SASS, as less is unfortunately not as robust as our team has learned through experience over the past few years. With many projects such as bootstrap also dropping less, I think that others agree.

Another common use case that we handle decently with Dojo 1.x is user customizable theming, or whitelabeling of an application. In that case, you typically have a variables.styl and then an overrides.styl which contains user or brand specific overrides for the theme.

That said, I'm diverging from the goal of the ticket which is the modularity of the CSS itself, preprocessed or not. I just think it's worth keeping in mind that we'll want clean mechanisms to override as well.

**Comment by kitsonk** [comment]
Agreed about keeping it focused on modularity, not pre-processors.  Issue #30 is opened to address this.

**Comment by mwistrand** [comment]
I agree with @devpaul that relying on a Radium-like methodology is problematic since it is an all-or-nothing approach to CSS that precludes many of the benefits of using a preprocessor/postprocessor. For example, if you wanted to use value-manipulating functions that preprocessors like Stylus or Sass execute at build time, you would either have to execute those functions at run time, or find/write another tool that can process those functions into static values (e.g., `{ color: lighten('#000', 0.5) }` => `{ color: '#010101' }`). As a result, I would prefer something like using CSS Modules (or even just a naming convention).

If we went with CSS Modules, there are a number of things the loader plugin would need to take into consideration, but I'll avoid enumerating them until there is a proper issue for it.

With regard to how styles might be structured in any foundational widget library, obviously each component would have its own file. Most of the component styles could be housed in dedicated files, but there would likely be reusable styles that would be better off as global selectors. For example, if we were to provide a basic modal widget that contained little more than a stack manager and some positioning styles, the Modal.css might look something like this:

```css
.common {
  z-index: 999;
}
.centered {
  composes: common;
  
  left: 50%;
  position: absolute;
  top: 50%;
  transform: translate(-50%, -50%);
}
```

Per the spec, these CSS classes would be converted to unique faux-local names; but for common styles like managing state, a set of global styles could be used. For example, the modal widget above would need a separate class for hiding the modal on close:

```css
/* state.css */
:global {
  .is-hidden {
    display: none;
  }
}
```

Assuming the build tool is able parse all usage of `styles.{selector}`, then it should still be possible to deliver a single CSS file with the application, as well as prevent inclusion of unused selectors.

**Comment by kitsonk** [comment]
> Assuming the build tool is able parse all usage of styles.{selector}

Right now (as per #10) I think we are leaning heavily towards `r.js`.  Given that and likely adopting the RequireJS builder API (see: dojo/loader#31) what would we need to do to get that?  Are you saying the builder would need to create a dependency graph of the styles?

From a builder plugin perspective, it is theoretically possible that the plugin can keep an internal state and hook [`onLayerEnd`](http://requirejs.org/docs/plugins.html#apionlayerend) to write out something.  Given that, do you think that is sufficient?

**Comment by mwistrand** [comment]
> From a builder plugin perspective, it is theoretically possible that the plugin can keep an internal state and hook `onLayerEnd` to write out something. Given that, do you think that is sufficient?

Apologies for the delay in responding. I have been testing this (using require js) with little success. The difficulty lies in the fact that the level of optimization I suggested requires that the parent module(s) requiring the custom `css` plugin be scanned for the styles that are actually used. If the parent module can be accessed, then theoretically it could be loaded as plain text, used to generate a syntax tree, and then filtered from there. I have not tested this `dojo/loader`, but if this sounds like a reasonable approach, I can look a little further down that rabbit hole to get a sense of whether it really is the best approach.

**Comment by kitsonk** [comment]
After a group discussion we have decided the path forward is:

* Adopt the CSS Module format for CSS modules
* Develop a tool, which we will make as part of our build chain which will generate a TypeScript module for each CSS module which can be imported into TypeScript code (see #66)
* This will allow for integration into the TypeScript language services as well as provide static analysis that can in theory allow us to optimise builds to only include the CSS being "required" by the project into the final built CSS for a project.

There are the advantages that this requires no specific loader plugins, as the meta data to reference the original class name will be generated as a JavaScript module in the appropriate format decided by the containing project and can also be build optimised.

**Comment by bitpshr** [comment]
CSS module support has been added with dojo/cli-build#17 and [dojo/cli-css-typings](https://github.com/dojo/cli-css-typings). Example usage can be found [here](https://gist.github.com/bitpshr/e80a01e36a26e78519fe8a53a0c24a5c).
