### ISSUE TITLE
Actively de-support IE9

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#40]
Originally, Dojo 2 planned to support IE9.  There are several challenges though to continue to support it:
- Flexbox is non existent, affecting planned widget layout
- Pushstate isn't supported, affecting the features of routing
- Lack of `classList` support (though dojo/dom doesn't depend on that anyways)

Therefore we should consider actively de-supporting it, meaning we stop testing against it and we try to remove code/feature tests we know are only working around IE9.

**Comment by kfranqueiro** [comment]
More on `classList`:

IIRC, we ultimately didn't rely on `classList` in dojo/dom in order to accommodate using `addClass`/etc. in SVG elements as well, but according to @jason0x43, IE9 is also the only browser that doesn't seem to support that in that context.

I had also thought I originally saw that TS's `SVGElement` type didn't include `classList`, but it seems as if now `classList` is part of `Element`, which `SVGElement` extends.  (Ref: https://github.com/Microsoft/TypeScript/blob/v1.8.10/lib/lib.dom.d.ts#L2955-L2956)

Meanwhile, one of the first headaches I had with IE9 was the lack of `Float32Array` for a simple `fround` shim in core.  The "else" part of the ternary in https://github.com/dojo/core/blob/c5f70a6/src/math.ts#L92-L110 exists solely for IE9, so we could remove some code in that area (and the accompanying `has` test, since this is all it's used for).

**Comment by kitsonk** [comment]
> FWIW but perhaps irrelevant, I had also thought I originally saw that TS's SVGElement type didn't include classList, but it seems as if now classList is part of Element, which SVGElement extends. (Ref: https://github.com/Microsoft/TypeScript/blob/v1.8.10/lib/lib.dom.d.ts#L2955-L2956)

I think they have started adopting the "living standard" when requested for these things, [which defines it  on `Element`](https://html.spec.whatwg.org/multipage/dom.html#dom) instead of relying on what came out of ChakraCore.  That does mean there are still going to be large holes when dealing with some parts of the DOM across browsers (and ergo the need for a toolkit or library to plaster over the cracks!)

**Comment by kitsonk** [comment]
Ok, we have had this open long enough.  Will resolve this.  We will actively desupport IE9 for Dojo 2.  I will try to get issues open for the things we need to remove.

**Comment by kitsonk** [comment]
It was brought up that we might want to re-consider supporting IE9.

**Comment by dylans** [comment]
Closing this again, we really don't want to add support for IE9/IE10 when other frameworks are actively removing their support for IE9/IE10 in newer releases.
