### ISSUE TITLE
Lambdas/Fat Arrow Functions

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#6]
I believe we agreed that we should only use lambdas/fat arrow functions when we need the canonical `this`.  If that is the case, we should add it to the guidelines.

**Comment by kfranqueiro** [comment]
Isn't this already noted?  See number 4-6 under https://github.com/dojo/guidelines/blob/master/STYLE.md#general

**Comment by kitsonk** [comment]
Ah, I looked for lambda or fat arrow or canonical `this`...  I guess we could/should add some examples of what a "good" use is and what a "unnecessary" use is.

**Comment by pdfernhout** [comment]
I will proceed to create examples, however that particular guideline is one I wondered about, given fat arrows are a selling point of JavaScript as syntactic sugar to reduce errors related to "this".

To provide more effective documentation, it might help to explain the reasoning behind the restriction. Is the concern something like this? Or is there another reason?
https://basarat.gitbooks.io/typescript/content/docs/arrow-functions.html
"Tip: Arrow Function Danger -- In fact if you want this to be the calling context you should not use the arrow function. This is the case with callbacks used by libraries like jquery, underscore, mocha and others. If the documentation mentions functions on this then you should probably just use a function instead of a fat arrow. Similarly if you plan to use arguments don't use an arrow function."

**Comment by kfranqueiro** [comment]
See also https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#arrow-functions, which perhaps goes out of its way to demonstrate how confusing it can be to determine whether it's "safe" or preferable to use a fat arrow function.

I could fathom adding "or if `this` needs to be bound within the callback" to rule 6 under general coding conventions in light of the case that both of these external sources bring up.

**Comment by pdfernhout** [comment]
I created pull request #19 with more examples for arrow functions.

@kfranqueiro I can make further changes if we can agree on a precise enough wording for revising rule 6. However, doesn't the parenthetical note already there of "e.g. for preservation across multiple nested scopes" cover binding `this` in a callback? That whole sentence seems a little confusing because it talks about increasing readability but the parenthetical note is about achieving functionality -- as in, how else would you reasonably deal with those nested scopes? Maybe an example there would help too.
