### ISSUE TITLE
Will Dojo2 be completely programmatic ?

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#65]
@RobertoMalatesta commented on [Wed Aug 17 2016](https://github.com/dojo/dojo2/issues/23)

@kitsonk one straight question:

will #dojo2 be completely programmatic?

I mean up to manipulating the single CSS attribute with a dot notation, without having to recur to CSS/HTML/BARFML and forget text based markup completely?

Thank you in advance.

--R

**Comment by kitsonk** [comment]
Moved this here, because this is where discussion of Dojo 2 really occurs...

We are looking at [CSS modules](https://github.com/css-modules/) for widgets that will help ensure that the dependency between a module and its CSS can be "enforced".  Though I think that isn't specifically what you are asking.

Because Dojo 2 widgets are virtual DOM based and we are using HyperScript versus markup for describing the DOM.  Overall, Dojo 2 is very "functionally" based.  But, for example CSS, we are doing our best to avoid inline styles, because they make it difficult to customise and change things.  The idea though is that an end developer would largely be abstracted from the need to know the inner workings of CSS or HTML and that a "division of labour" can occur where you could have a team member doing great CSS-foo, that they can do that in a way that fits well with those that focus on the TypeScript/JavaScript functionality.

[`dojo/app`](https://github.com/dojo/app), which is envisioned as the way for end-developers to orchestrate the building of applications will have both a functional DSL and a declarative DSL that can be done in markup.

**Comment by RobertoMalatesta** [comment]
Thank you for the answer @kitsonk ,
(oh, I did not mention which framework was the campy but I see you correctly identified it :P)

I will state my aim in more detail:

I write (basically) web enterprise applications for the finance.
These apps have to be rock solid and really fast to start with no file retrieve error

I currently have wrapped an OO layer onto SAP OpenUI5 components, hiding the behemoth behind   a nice TS OO structure that allows my application to compile into a single file and be up and running with a single GET.

By forgetting (most,at this time) CSS and HTML the app production is really simplified and I switched from using it for personal use to introducing it to clients that asked for it and  showed a big relief not getting into the ‘Nam that HTML/CSS/SASS-whatever is.

You fire up Visual Studio Code, or Webstorm and code completion guides you to creating applications (correct ones) in matters of hours.

What I learned from this approach is that if you simplify  development to a single language a lot of persons can be involved into their own company web development.

Next step is a visual tool, something that can work exactly like Delphi or -let me say it- Visual Basic 6 : a simple tool that allows common users to at least create the first version of an interface easily at a requirement gathering / prototyping stage.

Best tool that almost made it 10+ years ago was Tibco General Interface. 
But XSLT, low user-adoption and its company killed it.
Then Maquetta showed some promise, but that other company pulled the plug.
(BTW: I think I’m mentioning sth you know in detail since both the projects ended hosted by Dojo Foundation and Maquetta was dojo-based).

I strongly believe that the market and the web development needs simpler tools. Today more than ever.

To be as simple as possible it has to be single-language, and that language has to be strongly-typed,  with code completion / code assistants and no interaction with the cumbersomeness of CSS and HTML/XML formats.

For that language today we have plenty of choices:
TypeScript, or TypeScript or even TypeScript.
Let me stress it, since I just ported all my core apps to it (about 200k lines of code).

Since it can be used at a simple level it can be integrated into a web-based RAD for the end-user (office workforce+).
(I’m not excluding writing my own RAD, having the time).

On Dojo2:

Inline styles: you say you want to avoid them. I’m pro because some of them (like i.e. left or right alignment) are necessarily exposed programmatically for me since they could be triggered by an input, or by a particular value into a column.
Using CSS for that is a pain and would force users to learn where to change them, so no.

Besides, using separate CSSes means more files requested to the server and a receive error will result into skewy interfaces. I want them rock solid because my clients want them rock solid.

If the web app is a single file, the GET is a make or break, either you see the login page and that means everything's been downloaded, or you have to reload.

But once you’re inside the application there’s no chance of getting a 404 or a badly styled component.

Not to mention that you can closure.js it and somehow protect your code.


Dojo2 solution will undoubtedly have its own merits, just like Dojo 1 had, but from what you describe to me (thank you, BTW) it suffers the same defects I spotted in all the other frameworks (the campy one and UI5 first and foremost) of “complex item delivery issue”.

The division of work : if you have a RAD then it’s a matter of right-click and property change.
If you want you can have someone doing only that, but on enterprise applications it’s the same person that writes the code.


I hope to have been clear in this TLTR message, but I think that sharing ideas is always worth. And with persons like you, a pleasure.


– Roberto

**Comment by kitsonk** [comment]
> Inline styles: you say you want to avoid them. I’m pro because some of them (like i.e. left or right alignment, italic or bold) are necessarily exposed programmatically for me since they could be triggered by an input, or by a particular value into a column.

Those are human abstractions of visual styling.  By using inline styles you presume you know at design time how things should look from a UI perspective.  That would be considered anti-pattern for Dojo 2.  It is this sort of design-time hubris which limits the accessibility of components.  In Dojo 2, widgets apply the minimal amount of structural styles and even more minimal amount of inline styles.  Well designed components should need minimal API access to CSS and just try to express those as classes.  From a toolkit perspective, one person's inline style is another person's nightmare.  If you know all of the UI design constraints and have total control of the page, then inline styles might be fine.

> Besides, using separate CSSes means more files requested to the server and a receive error will result into skewy interfaces. I want them rock solid because my clients want them rock solid.

There are such things as build tools and bundling these days which can ensure that a production build could not suffer from this.  In addition, there are CI tools and test frameworks which can test all of your applications in browsers before you ever ship your code.

One of the things we are on heavy discussion at this moment is how do we couple widgets with their structural CSS, so that it will by dynamically available at run-time but also be able to be optimised into a build, as obviously that is a concern.

Defining inline styles programmatically (outside of it being design-time hubris) is also significantly less performant.

Again, what is good for a sole contributor is not good for a framework used by large teams.

> The division of work : if you have a RAD then it’s a matter of right-click and property change.
If you want you can have someone doing only that, but on enterprise applications it’s the same person that writes the code.

At this point, Dojo 2 is not planning a RAD, though it is not precluding an existence of one.  I don't think the Dojo Toolkit would take on the work, though I can easily see some sort of investment of a project to create something on top of [dojo/app](https://github.com/) as application should be able to be described in a JSON DSL.

The challenge though is that RAD environments make large assertions about how applications are created.  Dojo 1 fit that model fairly well, as Dijit represented that main way of creating applications, which was Forms and Controls.  Eventually MVP, MVC, MVVM made their way into the web, but in my opinion those application patterns a) aren't easily maintainable b) suffer from architecture breakage because of the constraints they impose and c) suffer from the fact you cannot cleanly break View from the Controller/View Model.  The Dojo 2 application architecture is a unidirectional data flow using "Widget 👉 Action 👉 Store 👉 Widget" concepts.  How these concepts can be effectively created in a UI is not clear at this point, but again, I suspect the Dojo Toolkit team wouldn't be the ones to do it as it needs a different focus.  That was one of the challenges we had with Dojo 1, eventually being everything to everyone.

**Comment by kitsonk** [comment]
Going to close this for now, can re-open if there are further thoughts or considerations.  Good comments and thoughts!

**Comment by RobertoMalatesta** [comment]
... damn, my fault. Been buried in a lot of things and wanted to have time to write some considerations, then it slipped out of the radar.
Thank you @kitsonk for the first-hand info ; I will follow the Dojo development sure it will turn out to a be a nice framework.

-- R

**Comment by kitsonk** [comment]
Feel free to revisit at any point... just doing a big issue triage!
